ktor:
    deployment:
        port: 8081
        host: 0.0.0.0
    application:
        modules:
            - com.example.ApplicationKt.module
    database:
        driver: org.h2.Driver
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
        username: root
        password: ""


